motion_capture_tracking_node:
  ros__parameters:
    type: "optitrack"
    hostname: "192.168.74.9"
    topics.frame_id: "world"
    topics.poses.qos.mode: "sensor"

    dynamics_configurations.default.max_velocity: [2.0,2.0,2.0]
    dynamics_configurations.default.max_angular_velocity: [3.14,3.14,3.14]
    dynamics_configurations.default.max_roll: 0.5
    dynamics_configurations.default.max_pitch: 0.5
    dynamics_configurations.default.max_fitness_score: 0.1

    marker_configurations.drone_marker.offset: [0.0,0.0,0.0]
    marker_configurations.drone_marker.points.0: [0.05,0.03,0.0]
    marker_configurations.drone_marker.points.1: [-0.05,0.03,0.0]
    marker_configurations.drone_marker.points.2: [0.00,-0.04,0.0]

    rigid_bodies.my_drone.initial_position: [0.0,0.0,0.0]
    rigid_bodies.my_drone.marker: "drone_marker"
    rigid_bodies.my_drone.dynamics: "default"